
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 30 12:17:32 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 19;
  public static final int except_word = 45;
  public static final int break_word = 38;
  public static final int assert_word = 37;
  public static final int Llave_c = 26;
  public static final int Op_booleano = 22;
  public static final int global_word = 49;
  public static final int Llave_a = 25;
  public static final int If = 8;
  public static final int elif_word = 43;
  public static final int return_word = 60;
  public static final int T_dato = 4;
  public static final int and_word = 36;
  public static final int Else = 9;
  public static final int flo_word = 56;
  public static final int Corchete_c = 28;
  public static final int Corchete_a = 27;
  public static final int is_word = 53;
  public static final int while_word = 62;
  public static final int yield_word = 64;
  public static final int raise_word = 59;
  public static final int While = 11;
  public static final int Division = 17;
  public static final int NumeroDecimal = 33;
  public static final int Int = 5;
  public static final int Cadena = 7;
  public static final int Float = 6;
  public static final int Parentesis_c = 24;
  public static final int def_word = 41;
  public static final int Parentesis_a = 23;
  public static final int For = 12;
  public static final int lambda_word = 54;
  public static final int not_word = 55;
  public static final int EOF = 0;
  public static final int P_coma = 30;
  public static final int exec_word = 46;
  public static final int class_word = 39;
  public static final int error = 1;
  public static final int try_word = 61;
  public static final int del_word = 42;
  public static final int Linea = 2;
  public static final int Op_atribucion = 20;
  public static final int with_word = 63;
  public static final int ERROR = 65;
  public static final int if_word = 50;
  public static final int else_word = 44;
  public static final int Do = 10;
  public static final int ElseIf = 35;
  public static final int from_word = 48;
  public static final int Op_logico = 18;
  public static final int pass_word = 57;
  public static final int nya = 34;
  public static final int in_word = 52;
  public static final int import_word = 51;
  public static final int Identificador = 31;
  public static final int Resta = 15;
  public static final int continue_word = 40;
  public static final int finally_word = 47;
  public static final int Multiplicacion = 16;
  public static final int Op_incremento = 21;
  public static final int Numero = 32;
  public static final int Suma = 14;
  public static final int print_word = 58;
  public static final int Main = 29;
  public static final int Igual = 13;
  public static final int Comillas = 3;
}

